# Generated by Django 5.2.17 on 2026-10-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
    ]
