# Generated by Django 5.2.17 on 2026-10-02 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_service_canonical_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=180)),
                ('budget', models.CharField(blank=True, choices=[('under_2500', 'Under $2,500'), ('2500_5000', '$2,500-$5,000'), ('5000_10000', '$5,000-$10,000'), ('over_10000', '$10,000+'), ('not_sure', 'Not sure yet')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=250)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_contacted', models.BooleanField(default=False)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
