# Generated by Django 5.2.17 on 2026-10-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='budget',
            field=models.CharField(blank=True, choices=[('under_100000', 'Under INR 1 lakh'), ('100000_300000', 'INR 1-3 lakh'), ('300000_1000000', 'INR 3-10 lakh'), ('over_1000000', 'INR 10 lakh+'), ('not_sure', 'Not sure yet')], max_length=20),
        ),
    ]
