# Generated by Django 5.2.17 on 2026-10-02 22:07

import django.db.models.deletion
from django.db import migrations, models


def preserve_legacy_contact_status(apps, schema_editor):
    ContactMessage = apps.get_model("contact", "ContactMessage")
    alias = schema_editor.connection.alias
    ContactMessage.objects.using(alias).filter(is_contacted=True).update(status="contacted")


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactmessage_budget'),
        ('services', '0003_seed_service_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='source',
            field=models.CharField(default='website', max_length=120),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('closed', 'Closed')], db_index=True, default='new', max_length=12),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(preserve_legacy_contact_status, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_contacted',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_read',
        ),
        migrations.CreateModel(
            name='ProjectEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=180)),
                ('budget', models.CharField(blank=True, choices=[('under_100000', 'Under INR 1 lakh'), ('100000_300000', 'INR 1-3 lakh'), ('300000_1000000', 'INR 3-10 lakh'), ('over_1000000', 'INR 10 lakh+'), ('not_sure', 'Not sure yet')], max_length=20)),
                ('timeline', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
                ('source', models.CharField(default='website', max_length=120)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('closed', 'Closed')], db_index=True, default='new', max_length=12)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_enquiries', to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
