# Generated by Django 5.2.17 on 2026-10-02 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_sitesettings_facebook_url_sitesettings_instagram_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='site/')),
                ('description', models.CharField(default='Digital systems for the next generation.', max_length=240)),
                ('copyright_text', models.CharField(blank=True, max_length=180)),
                ('show_social_links', models.BooleanField(default=True)),
                ('show_whatsapp', models.BooleanField(default=True)),
                ('show_email', models.BooleanField(default=True)),
                ('show_phone', models.BooleanField(default=True)),
                ('show_address', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'footer settings',
                'verbose_name_plural': 'footer settings',
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('url', models.CharField(blank=True, help_text='Internal path, starting with /', max_length=300)),
                ('external_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])])),
                ('is_external', models.BooleanField(default=False)),
                ('is_cta', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=60)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('keywords', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('x', 'X'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('url', models.URLField(validators=[django.core.validators.URLValidator(schemes=['https', 'http'])])),
                ('icon', models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('x', 'X'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], max_length=20)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('open_new_tab', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='x_url',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_og_image',
            field=models.ImageField(blank=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_seo_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.FileField(blank=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_description',
            field=models.CharField(default='Digital systems for the next generation.', max_length=240),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='search_console_verification',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
