# Generated by Django 5.2.17 on 2026-10-02 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_seed_site_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='organization_name',
            field=models.CharField(default='NXTWALK', max_length=120, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=24, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\s().-]{8,24}$', 'Enter a valid WhatsApp number.')]),
        ),
    ]
