# Generated by Django 5.2.17 on 2026-10-02 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_sitesettings_organization_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('company', 'Company'), ('services', 'Services'), ('resources', 'Resources')], max_length=16)),
                ('title', models.CharField(max_length=80)),
                ('url', models.CharField(blank=True, help_text='Internal path, starting with /', max_length=300)),
                ('external_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])])),
                ('is_external', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['section', 'display_order', 'id'],
            },
        ),
    ]
