# Generated by Django 5.2.17 on 2026-10-02 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=60)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('keywords', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('industry', models.CharField(max_length=120)),
                ('strategy', models.TextField()),
                ('implementation', models.TextField()),
                ('technology', models.TextField(blank=True)),
                ('seo_strategy', models.TextField(blank=True)),
                ('marketing_strategy', models.TextField(blank=True)),
                ('results', models.TextField()),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_study', to='portfolio.project')),
            ],
            options={
                'ordering': ['-published_at', 'project__title'],
            },
        ),
    ]
